security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        jamn_area_publica:
             pattern: ^/(registro|activar|tarifas|contratar|login$)
             security: false

        jamn_area_protegida:
             pattern: ^/
             anonymous: ~
             provider: in_memory
             http_basic:
                realm: "Secured Demo Area"

#             form_login:
#                login_path:  /notas/login
#                check_path:  /notas/login_check

#        logout:
#             path:   /logout
#             target: /

    access_control:
        - { path: ^/notas/miespacio, roles: ROLE_PREMIUM }
        - { path: ^/notas/administracion, roles: ROLE_ADMIN, requires_channel: https }
        - { path: ^/notas, roles: ROLE_REGISTRADO }