security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Jazzyweb\NotasFrontendBundle\Entity\Usuario: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        ROLE_PREMIUM: [ ROLE_REGISTRADO ]

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

        base_datos:
           entity: { class: JazzywebNotasFrontendBundle:Usuario, property: username }


    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        jamn_area_publica:
             pattern: ^/(registro|activar|tarifas|contratar|login$)
             security: false

        jamn_area_protegida:
             pattern: ^/
             anonymous: ~
             provider: base_datos
             form_login:
                login_path:  /login
                check_path:  /login_check

             logout:
                path:   /logout
                target: /

#             provider: in_memory
#             http_basic:
#                realm: "Secured Demo Area"

    access_control:
        - { path: ^/miespacio, roles: ROLE_PREMIUM }
        - { path: ^/administracion, roles: ROLE_ADMIN, requires_channel: https }
        - { path: ^/, roles: ROLE_REGISTRADO }